name: Send a Tweet
on:
  push:
    tags:
      - '*'
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "I have completed a new challenge  \" ${{ github.event.head_commit.message }} \" #CodexJavaScript30 @wesbos @ManuCastrillonM https://vasquezlab.github.io/JavaScript30/"
          consumer-key: le2dxNv5cffvRpyC9hd915Inl
          consumer-secret: REt9LyFyy1C9I1D6Furl5OW3zbZkdTFbG42nYu7blNFBFGdH7n
          access-token: 197966686-kc53FZx3OPMq9eVqVxZTYrONmIPNIWr7cndFgsi9
          access-token-secret: 7bDxzXcLRfCsMbdlAwLrVL4h2nbWCPY4Z3MAryNqpRju6
